<?php

namespace CorreoBundle\Repository;

/**
 * CorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorreoRepository extends \Doctrine\ORM\EntityRepository
{
}
