<?php

namespace CorreoBundle\Repository;

/**
 * EstadoCorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCorreoRepository extends \Doctrine\ORM\EntityRepository
{
}
