<?php

namespace CertBundle\Repository;

/**
 * AccesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesoRepository extends \Doctrine\ORM\EntityRepository
{
    public function ultimoAcceso($usuario_id){
        $em = $this->getEntityManager();
		$db = $em->getConnection();
        $query = " select fcacceso from cert_acceso where " 
                ." id = (select max(id) from cert_acceso where usuario_id = :usuario_id)";
        $stmt = $db->prepare($query);
		$params = [":usuario_id" => $usuario_id];
		$stmt->execute($params);
		$po = $stmt->fetch();
        if ($po){
            return $po['fcacceso'];
        } else {
            return false;
        }
    }
}
