<?php

namespace CertBundle\Repository;

/**
 * FicheroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheroRepository extends \Doctrine\ORM\EntityRepository {

    public function queryByUsuario($usuario_id) {
        $em = $this->getEntityManager();
        $db = $em->getConnection();
        $query = " select cert_ficheros.id as id , "
                . "  cert_ficheros.dni as dni ,"
                . " cert_ficheros.fichero as fichero from cert_ficheros "
                . " inner join cert_usuario on cert_usuario.dni = cert_ficheros.dni "
                . " where cert_usuario.id = :usuario_id";
        $stmt = $db->prepare($query);
        $params = [":usuario_id" => $usuario_id];
        $stmt->execute($params);
        $po = $stmt->fetch();
        if ($po) {
            return $po;
        } else {
            return false;
        }
    }

}
