<?php

namespace CertBundle\Repository;

/**
 * LogDescargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogDescargaRepository extends \Doctrine\ORM\EntityRepository
{
}
